### ISSUE TITLE
Hỗ trợ dòng android 4.0 trở lên

### ISSUE THREAD

**Issue by ducsatthu** [duytung1009/NCKH2016#1]
Anh nghĩ là nên làm cho các dòng điện thoại chạy android từ 4.0 trở lên vì có một số dòng điện thoại sài android khác không thể nâng cấp máy như hàng FPT chẳng hạn không sử dụng đc thì rất phí vả lại thị dòng diện thoại sử dụng android 4.0 vẫn còn lớn với 2.5 % người sử dụng http://developer.android.com/about/dashboards/index.html

**Comment by Tuong94** [comment]
dear sir.
sir thay điện thoại đi sir !

2016-03-28 10:36 GMT+07:00 duytung1009 notifications@github.com:
